# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\pwr22\zoom

environment:
  GOPATH: c:\gopath

stack:
  - go 1.10
  - go 1.11

before_test:
  - go get ./...
  - go vet ./...

test_script:
  - go test ./...
