# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\pwr22\go-zoom

environment:
  GOPATH: c:\gopath

stack:
  - go 1.12
  - go 1.13

before_test:
  - go get ./...
  - go vet ./...

test_script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_test:
  - choco install codecov
  - codecov -f coverage.txt